## Static

- type: latheRecipePack
  id: NSServiceBoardsStatic
  recipes:
  - BiogeneratorMachineCircuitboard
  - NSUniformPrinterMachineCircuitboard
  - MicrowaveMachineCircuitboard
  - OvenMachineCircuitboard
  - StoveMachineCircuitboard
  - ReagentGrinderMachineCircuitboard
  - ElectricGrillMachineCircuitboard
  - BoozeDispenserMachineCircuitboard
  - SodaDispenserMachineCircuitboard
  - SmartFridgeCircuitboard